### ISSUE TITLE
500 server error

### ISSUE THREAD

**Issue by innocuous** [marinaglancy/moodle-format_flexsections#48] opened 2023-03-22 06:14 UTC
Installing on moodle 4.1.2 gives me http 500 error ONLY when loggin in as admin.
Students are able to login fine.
Only solution is to remove/rename the flexsections folder and then I can login as admin again.

**Comment by marinaglancy** [comment] 2024-10-02 10:10
sorry for leaving this unattended. I'm cleaning up the backlog now. Unfortunately there were no reproduction instructions provided here, no information about the version of the format_flexsections, no backtrace of the error. Since it was a single report, I assume that the problem was in mismatching version or a conflict with another plugin. I'm closing this issue since I can not reproduce it

**Closed as completed by marinaglancy** 2024-10-02 10:10 UTC
