### ISSUE TITLE
Index (left sidemenu) disapears for students when using restrict access

### ISSUE THREAD

**Issue by alosFAK** [marinaglancy/moodle-format_flexsections#89] opened 2024-09-08 18:30 UTC
When restrict access has been set up to one or more sections where students must complete or pass an activity, the content in the index side menu disappears  (white page with no content - only students). This happens in all courses using Flex sections format and when using restrict access in sections (not in activities).
This error is not present in other formats (Custom sections f.x.). What could be wrong?
I use Moodle 4.4. and Flex section ver. 4.1.0.

**Comment by marinaglancy** [comment] 2024-10-02 19:28
Thanks for the report and thanks for the very clear reproduction steps. 
Apparently the problem was much bigger than this, any subsections or activities in subsections were not properly hidden if the section had restrictions but was still displayed on the course page.

This was fixed in new version of the plugin v4.1.1

**Closed as completed by marinaglancy** 2024-10-02 19:28 UTC
