### ISSUE TITLE
Section summary displaying on main course page for some users, not displaying for others

### ISSUE THREAD

**Issue by ashakinney** [marinaglancy/moodle-format_flexsections#68] opened 2023-07-31 20:48 UTC
Hi Marina- We're seeing some confusing behavior about whether or not a section summary will display on the main course page when the section is set to "display as a link". Some users see the summary displayed on the main course page, others do not.

Example course viewed by two different users below. You can see the student view on the left is different from the instructor view on the right. I've seen similar things with two different instructors- one person sees the summary displayed, the other does not.

Any idea what is causing this? Thanks!

Asha 
Amherst College
[Screen Shot 2023-07-31 at 4 33 50 PM](https://github.com/marinaglancy/moodle-format_flexsections/assets/35937323/83dfadbc-b55a-4f14-b6ab-0ada4d4069aa)

**Comment by VOOM108** [comment] 2024-01-22 14:11
This seems true for us, too. In this case, out of the 5 sections that are displayed as links, only the first .course-content-item-content.collapse has a class of .show - I tried to remove the .collapse:not(.show) { display: none; } but since I cannot find a way to discern sections that are displayed on the course page from those displayed as links, that would remove the summarytext etc. from the sections that are to be displayed on the course page as well.

**Comment by marinaglancy** [comment] 2024-10-02 20:57
Hello, thanks for the report and sorry for not replying earlier.

I can see why this is happening and here are the reproduction instructions:

- As a teacher create a course with several sections that are displayed on the course page (not as a link)
- As a student view the course and collapse some of the sections
- As a teacher change the sections to be displayed as a link
- As a student view the course again. Even though you no longer have an option to collapse/expand the sections, the preferences about the collapsed state are still stored and they apply to the new view. The sections which you have previously collapsed now do not have a visible description.

The solution is to ignore the collapsed preference when the section is displayed as a link

**Comment by marinaglancy** [comment] 2024-10-06 21:29
This is fixed in v4.1.2
Thanks for the report

**Closed as completed by marinaglancy** 2024-10-06 21:29 UTC
Labels: bug
